{% set name = "miss3d" %}
{% set version = "6.7" %}
{% set sha256 = "518a9072af34df49015b976345e15251c62820900a2bf2a3088e323bfbab6a61" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://downloads.sourceforge.net/project/prereq/miss3d-{{ version }}_aster4.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [osx or win]
  detect_binary_files_with_prefix: True   

requirements:
  build:
    - {{ compiler('gfortran') }}  # [linux]
  host:
    - make  # [not win]
    - ninja  # [win]
    - liblapack
    - libblas
  run:
    - liblapack
    - libblas
test:
  commands:
    - $PREFIX/bin/run_miss3d || true  # [linux]

about:
  home: https://www.code-aster.org/spip.php?article98
  license: CECILL-C
  license_family: GPL
  license_file: ./LICENSE.txt
  summary: 'MISS, un outil performant en génie parasismique, dynamique des structures et géophysique'
  description: |
    Soil-Structure Interactions (ISS) and Sol-Fluid-Structure (ISFS) involved in buildings dynamics or in arch dams, 
    can be resolved with frequency coupling in Code_Aster.
    MISS3D (called via the Code_Aster command CALC_MISS) 
    is a code with integral equations (Green functions) and sub-structuring from ECP / LMSSMat .  
  doc_url: https://www.code-aster.org/IMG/UPLOAD/DOC/Telechargement/notice_util_miss3d_v6.4.pdf

extra:
  recipe-maintainers:
    - ldallolio
